#!/bin/bash

bs() {
    local pattern="$1"

    if [ -z "$pattern" ]; then
        echo "bs: branch pattern required"
        return 1
    fi

    local branches=($(git branch | sed "s#*##" | grep "$pattern"))

    if [ ${#branches[@]} -eq 0 ]; then
        branches=($(git branch -r | grep "$pattern" | sed 's#origin/##g'))
    fi

    echo "${branches[@]}"
}

bs "$@"