#!/bin/bash

cmt() {
    local msg="$1"
    local ns="$2"
    local ticket="$(tkt)"

    if [ -z "$msg" ]; then
        echo "commit message required"
        return
    fi

    if [ $(git status | grep -c "nothing to commit, working tree clean") -eq 1 ]; then
        pass "Changes already committed" --color
        return
    fi

    if [ ! -z "$ticket" ]; then
        msg="$ticket: $msg"
    fi

    x "git add ." "Stage all changes for commit"

    if [ ! -z "$ns" ]; then
        x "vendor/bin/phpcs 2>&1" "Run code sniffer"

        if [ $? -eq 0 ]; then
            echo -e "\nFix code sniffer issues and rerun gitcom"
            return 1
        fi
    fi

    x "git commit -m '$msg'" "Commit all staged changes"
    x "git push" "Push all committed changes"
}

cmt "$@"