#!/bin/bash

seconds_to_timestamp() {
    local total_seconds="$1"
    local minutes=$((total_seconds / 60))
    local seconds=$((total_seconds % 60))
    
    printf "%02d:%02d" "$minutes" "$seconds"
}

pause() {
    local start_time=$(date +%s)
    local elapsed=0
    local iteration_count=0
    local spin_chars=('-' '\' '|' '/')

    while true; do
        osascript -e '
            tell application "Warp"
                activate
            end tell
            delay 0.2
            tell application "System Events"
                tell process "Warp"
                    keystroke "..."
                    delay 0.1
                    key code 51
                    delay 0.1
                    key code 51
                    delay 0.1
                    key code 51
                end tell
            end tell
        '
        # Show spinner for about 20 seconds
        for ((i=0; i<20; i++)); do
            for c in "${spin_chars[@]}"; do
                printf "\r%s" "$c"
                sleep 0.25
            done
        done
        printf "\r                \r"  # Clear spinner line

        elapsed=$(( $(date +%s) - start_time ))
        iteration_count=$((iteration_count + 1))
        printf "%d\t- Paused for %s\n" "$iteration_count" "$(seconds_to_timestamp "$elapsed")"
    done
}

pause "$@"